### ISSUE TITLE
Manga Demon not working, chapters not loading

### ISSUE THREAD

**Issue by uowis-b** [TheNetsky/Netskys-Extensions#91]
**Describe the bug**
MangaDemon not working, chapters not loading

**To Reproduce**
1. Go to MangaDemon
2. Click on any manga
3. Scroll down to 'chapters'

```
Paperback: JSError Error
[PaperbackError(300)] JSError
Error: Couldn't find any chapters for mangald: I-am-with-the-music-immortals-VA47!'
```

**Expected behavior**
Chapters should load

**Screenshots/Video**
![IMG_1353](https://github.com/TheNetsky/netskys-extensions/assets/13195330/7638c202-960a-4307-8e4a-e6e35e66754c)

**App version**
- v0.8.6-r2

**Source WITH source version**
- MangaDemon 1.0.4

**Comment by uowis-b** [comment]
Probably just change

 `const MD_DOMAIN = 'https://manga-demon.org';`
 
 to  
 
 `const MD_DOMAIN = 'https://demoncomics.org`

**Comment by henderea** [comment]
@uowis-b You might consider making a pull request yourself for the change. That would make netsky happy, since he would just need to merge it. You should aim to test it yourself before sending the PR, though. It's only a matter of time before netsky stops updating sources himself, so we should all get in the habit of making PRs since merging will likely soon be the limit of what he'll do.
